In [1]:
x=1

In [2]:
y=2

In [5]:
print(x+y)

3


In [6]:
p = True

In [7]:
q= False

In [8]:
(p or q) and (not p)

False

In [9]:
nombre = "Luis"

In [10]:
1/0

ZeroDivisionError: division by zero

In [12]:
import numpy as np

In [13]:
np.pi

3.141592653589793

In [14]:
np.e

2.718281828459045

In [15]:
np.inf

inf

In [16]:
1/np.inf

0.0

In [17]:
np.inf - np.inf

nan

In [18]:
np.sin(3*np.pi)

3.6739403974420594e-16

In [19]:
np.sqrt(-1)

/home/docente/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [20]:
np.log(np.e)

1.0

In [22]:
a=np.array([3, 4 ,5])

In [23]:
a.shape

(3,)

In [24]:
np.divide(3,2)

1.5

In [25]:
np.divide(3,0)

/home/docente/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


inf

In [26]:
a[0]

3

In [27]:
a[1]

4

In [28]:
a[2]

5

In [29]:
2*a+3

array([ 9, 11, 13])

In [30]:
b=np.array([-1,2,1])

In [31]:
np.dot(a,b)

10

In [32]:
a @ b

10

In [33]:
a.T

array([3, 4, 5])

In [44]:
c = np.array([[1,0,0],b,a])

In [45]:
c.shape

(3, 3)

In [46]:
c.T

array([[ 1, -1,  3],
       [ 0,  2,  4],
       [ 0,  1,  5]])

In [47]:
b.shape

(3,)

In [48]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])